### ISSUE TITLE
Concurrent requests to Buddy get stuck

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/manticoresearch-buddy#274] opened 2024-05-06 06:53 UTC
### Bug Description:

If we already have a request being processed with Buddy and send another one to it, the second request gets stuck as well.

To reproduce on the `dev2` server:

// Start Manticore with Buddy
`docker run -d --rm --name=manticore-test -p 9408:9308 -e EXTRA=1 manticoresearch/manticore:dev`

// Running first request to stuck
`curl localhost:9408/cli -d 'debug sleep 30'`

// Running second request concurrently
`curl localhost:9408/cli -d 'show tables'`

Also, the issue doesn't seem to be reproducible on MacOS.

### Manticore Search Version:

Manticore 6.2.13 8c6cec329@24050309 dev

### Operating System Version:

Ubuntu 22.04 LTS

### Have you tried the latest development version?

- [X] Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Task estimated
- [x] Specification created, reviewed, and approved
- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation proofread
- [x] Changelog updated

</details>

**Comment by Nick-S-2018** [comment] 2024-05-06 06:58
Related to #271

**Comment by Nick-S-2018** [comment] 2024-05-06 11:28
Probably, it would make sense for testing to log requests on daemon side right before it writes them to the Buddy connection's tcp socket, and on Buddy side right after Swoole server reads them from the socket. It would help to finally find out where the problem arises.

**Comment by donhardman** [comment] 2024-05-08 10:17
I've rewritten the codebase to use a native Swoole client. This is the correct way to address the potential locking issue.
Here are the pull requests for review:
* https://github.com/manticoresoftware/buddy-core/pull/45
* https://github.com/manticoresoftware/manticoresearch-buddy/pull/277

First, we need to verify that this resolves the problem. I also found an issue on the daemon side. To confirm the fix, I recommend using debug sleep 30 followed by a direct request to Buddy to ensure it's working as expected.


Here's a Minimal Reproducible Example (MRE) for the daemon issue:

It seems we can only reproduce this on the first run.

Steps to reproduce:
* Run searchd.
* In two separate windows, run the following commands:
```bash
curl localhost:9308/cli -d 'debug sleep 30'
```
and
```bash
port=[INSERT BUDDY PORT HERE] 
curl -H 'Content-type: application/json' 127.0.0.1:$port -d '{"tnown json request","error":"","version":2,"message":{"path_query":"/sql?mode=raw","body":"show queries","http_method":"POST"}}'; curl localhost:9308/cli -d 'show queries';
```
You'll notice that Buddy responds while the request going through the daemon hangs.

Attempting to reproduce this without restarting the server will not work.

**Comment by donhardman** [comment] 2024-05-08 10:35
Hey @Nick-S-2018,

Can you verify that the `fix/concurrency` branch resolves the Buddy issue and allows for direct calls? Remember to update with `composer update` since there were core changes.  Also, could you review the code changes and pull requests? Thanks!

**Comment by Nick-S-2018** [comment] 2024-05-08 11:26
@donhardman 
I confirm that those cases of hung requests which, from my tests, were caused by delay on Buddy side, cannot be reproduced with the new Buddy branch now.
Yes, code changes look fine for me.

**Comment by donhardman** [comment] 2024-05-08 11:37
To ensure our performance remained top-notch after switching to Swoole on our server, I dug into our old benchmarks and ran them again for comparison. Check out the results:

Buddy from the main branch

```
Running 1m test @ http://127.0.0.1:36273/
  2 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    57.02ms  182.25ms   1.04s    91.80%
    Req/Sec     6.66k     2.18k    9.97k    55.87%
  786402 requests in 1.00m, 499.36MB read
Requests/sec:  13106.26
Transfer/sec:      8.32MB
```

Buddy from the `fix/concurrent` branch

```
Running 1m test @ http://127.0.0.1:40609/
  2 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.65ms   31.51ms 377.65ms   97.62%
    Req/Sec     6.74k   822.50     7.69k    98.05%
  793999 requests in 1.00m, 1.29GB read
Requests/sec:  13232.79
Transfer/sec:     22.07MB
```

We can see that the new branch shows better results with much lower latency.

We're seeing an increase in data transfer. This is likely due to the switch to Keep-Alive, which improves latency but also results in more data being transferred. This seems to be how Manticore handles connections, as the test was performed using `show queries`.

**Comment by Nick-S-2018** [comment] 2024-05-08 11:39
@tomatolog 
These last updates in Buddy aren't merged to the master branch yet, so you may want to wait until it's done before starting your tests.

**Comment by sanikolaev** [comment] 2024-05-08 11:51
> with much lower latency

But about the same RPS. But anyway it's good. The new performance is more stable (stdev is much lower). What I don't understand which could affect the test is `1.29GB` vs `499.36MB`

**Comment by donhardman** [comment] 2024-05-08 11:53
The transfer seems to be influenced by the output of "show queries." My guess is that with `Keep Alive` connections, the daemon might return more rows while the connection is active. However, it's best to confirm this or check with other developers.

**Comment by donhardman** [comment] 2024-05-08 12:07
The results for `show version`

`main`:
```
Running 1m test @ http://127.0.0.1:35739/
  2 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   106.69ms  249.91ms   1.81s    86.78%
    Req/Sec     8.98k     2.20k   13.27k    79.17%
  823495 requests in 1.00m, 510.47MB read
Requests/sec:  13719.97
Transfer/sec:      8.50MB
```

`fix/concurrent`:
```
Running 1m test @ http://127.0.0.1:36323/
  2 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   101.08ms  241.54ms   1.85s    87.25%
    Req/Sec     9.09k     2.38k   18.83k    74.68%
  1005942 requests in 1.00m, 623.57MB read
  Socket errors: connect 0, read 0, write 0, timeout 4
Requests/sec:  16761.22
Transfer/sec:     10.39MB
```

**Comment by sanikolaev** [comment] 2024-05-15 10:38
@tomatolog pls proceed with reproducing and fixing the issue in daemon described here https://github.com/manticoresoftware/manticoresearch-buddy/issues/274#issuecomment-2100245295

**Comment by tomatolog** [comment] 2024-05-15 13:49
when I try to investigate issue I see that combo
terminal1
```
curl "127.0.0.1:9308/cli" -d "debug sleep 30"
```
terminal2
```
curl -H "Content-type: application/json" "127.0.0.1:9412" --data-binary @buddy1.js && curl "127.0.0.1:9308/cli" -d "show queries";
```

hungs on the `show queries`

However it is impossible to investigate issue as buddy flushes daemon with the `sharding` and `ping` requests.
If I issue the `mysql -h 127.0.0.1 -P 9315 -vvv -e "DISABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-sharding"` first then the combe works fine.

I need reproducible example alone as it got mixed with all other requests from buddy the flow is not clear.

**Comment by donhardman** [comment] 2024-05-15 13:51
You can try disabling `--debugv` or `--debug` in Buddy because the query g makes to Buddy hangs on the daemon side. Disabling it will clean up the output, and in this case, we only need to debug it on the daemon side.

**Comment by tomatolog** [comment] 2024-05-15 13:54
without `--debug` the flow is also not clear as I not sure these `ping` and `sharding` requests are related to this issue or not and why `sharding`  requests works as usual but `show queries` stuck

**Comment by donhardman** [comment] 2024-05-17 04:37
So in that case we can just use Buddy from sources and in the `src/init.php` file comment the next line:

`	'manticoresoftware/buddy-plugin-sharding',`

**Comment by sanikolaev** [comment] 2024-05-21 05:38
@tomatolog with the newest buddy version (in the main branch) you can now do so:
```
	g_sStartArgs.SetSprintf ( "%s --listen=%s --bind=%s %s --threads=%d --skip=manticoresoftware/buddy-plugin-sharding --skip=manticoresoftware/buddy-plugin-queue",
```
(see `--skip`) to avoid loading the sharding plugin. I've tested it within this PR https://github.com/manticoresoftware/manticoresearch/pull/2206/files.

**Comment by tomatolog** [comment] 2024-05-21 15:32
with the master head of daemon and buddy with disabled sharding I see that is the curl issue

sometimes curl went to write immediately 
```
[Tue May 21 15:14:34.647 2024] [16920] q: show queries
[Tue May 21 15:14:34.647 2024] [16920] q > buddy: {"type":"unknown json request","error":"","version":2,"message":{"path_query":"/cli","body":"show queries","http_method":"POST"}}
[Tue May 21 15:14:34.647 2024] [16920] CurlConn_t::RunQuery @ 544 0x000001934515d9c0(0x0000019346f687a0) (http://host.docker.internal:9412) Add to multi 0x00007ff627b2fa40 for http://host.docker.internal:9412
[Tue May 21 15:14:34.647 2024] [16920] CurlConn_t::RunQuery @ 547 0x000001934515d9c0(0x0000019346f687a0) (http://host.docker.internal:9412) Add complete -> 0
[Tue May 21 15:14:34.647 2024] [16920] WARNING: CurlMulti_c::SocketAction @ 572 invoke curl_multi_socket_action with socket 18446744073709551615, NONE
[Tue May 21 15:14:34.648 2024] [16920] CurlMulti_c::CmSocketCb @ 601 called with sock 2392 for IN(1), data 0x0000000000000000
[Tue May 21 15:14:34.648 2024] [16920] CurlMulti_c::MakeAsyncSocket @ 591 called with sock 2392
[Tue May 21 15:14:34.648 2024] [16920] CurlSocket_t::CurlSocket_c @ 339 0x000001934600d9e0 (refs 1, sock 2392) 
[Tue May 21 15:14:34.648 2024] [16920] CurlMulti_c::WriteSocketCookie @ 270 curl_multi_assign for socket 2392, cookie 0x000001934600d9e0 returned 0

```

other time curl stuck at `CurlMulti_c::SocketAction @ 575 curl_multi_socket_action returned 0, 2 tasks running.` waiting external event (reply receive) to happen
```
[Tue May 21 15:13:15.829 2024] [16920] q: show queries
[Tue May 21 15:13:15.829 2024] [16920] q > buddy: {"type":"unknown json request","error":"","version":2,"message":{"path_query":"/cli","body":"show queries","http_method":"POST"}}
[Tue May 21 15:13:15.829 2024] [16920] CurlConn_t::RunQuery @ 544 0x000001934515d1a0(0x0000019346f6c150) (http://host.docker.internal:9412) Add to multi 0x00007ff627b2fa40 for http://host.docker.internal:9412
[Tue May 21 15:13:15.829 2024] [16920] CurlConn_t::RunQuery @ 547 0x000001934515d1a0(0x0000019346f6c150) (http://host.docker.internal:9412) Add complete -> 0
[Tue May 21 15:13:15.829 2024] [16920] WARNING: CurlMulti_c::SocketAction @ 572 invoke curl_multi_socket_action with socket 18446744073709551615, NONE
[Tue May 21 15:13:15.829 2024] [16920] WARNING: CurlMulti_c::SocketAction @ 575 curl_multi_socket_action returned 0, 2 tasks running.
[Tue May 21 15:13:39.883 2024] [8444] WARNING: CurlSocket_t::NotifyCurl @ 393 0x000001934600d950 (refs 1, sock 2340) got events 1, IN
[Tue May 21 15:13:39.883 2024] [9396] WARNING: CurlMulti_c::SocketAction @ 572 invoke curl_multi_socket_action with socket 2340, IN
[Tue May 21 15:13:39.883 2024] [9396] WARNING: CurlConn_t::WriteCb @ 463 0x000001934515d000(0x0000019346f6e5a0) (http://host.docker.internal:9412) received 205 bytes
```

I not sure is it the curl issue or our implementation is wrong maybe @klirichek could check and provide some insights

**Comment by tomatolog** [comment] 2024-05-22 14:26
should be fixed at the daemon https://github.com/manticoresoftware/manticoresearch/commit/bb40ff7a14531d30e29875c482b12990d22a3187 there I disabled CURL_PIPEWAIT option

**Comment by sanikolaev** [comment] 2024-05-24 03:35
> Changelog updated

Updated https://docs.google.com/spreadsheets/d/1mz_3dRWKs86FjRF7EIZUziUDK_2Hvhd97G0pLpxo05s/edit?pli=1#gid=1102439133

@PavelShilin89 pls add a test for this issue.

**Comment by PavelShilin89** [comment] 2024-05-29 14:08
Done in https://github.com/manticoresoftware/manticoresearch/pull/2253

**Closed** 2024-05-29 14:08 UTC
Labels: bug, rel::upcoming
