### ISSUE TITLE
The fuzzy option does not work via HTTP CLI and JSON API 

### ISSUE THREAD

**Issue by PavelShilin89** [manticoresoftware/manticoresearch-buddy#411] opened 2024-12-09 03:09 UTC
### Bug Description:

Incorrect processing of requests in HTTP CLI and JSON API interfaces when using constructs with option fuzzy=1.

### MRE:
Create a table and insert data:
```
mysql -P9306 -h127.0.0.1 -e "drop table if exists products; create table products(f text) min_infix_len='2'; insert into products values(1, 'ящык');"
```
Execute the following HTTP JSON API query:
```
curl -s -X POST "0:9308/sql" -H "Content-Type: application/json" -d '{"query": "select * from products where match(\'ящик\') option fuzzy=1"}'
```
Execute a basic query via the JSON API:
```
curl -s -X POST "0:9308/sql" -H "Content-Type: application/json" -d "{\"query\": \"select * from products\"}"
```

**Current Result:**
1. For HTTP CLI (/cli):
```
ERROR: Invalid options in query string, make sure they are separated by commas
```
 2.For HTTP JSON API (/sql):
```
{"error":"P02: syntax error, unexpected $undefined near '(null)'"}
```

**Expected Result:**
```
{
  "id": 1,
  "f": "ящык"
}
```

Additional Notes:
	•	The fuzzy option works as expected when used via the MySQL CLI interface:
```
mysql -P9306 -h127.0.0.1 -e "select * from products where match('ящик') option fuzzy=1;"
```
Output
```
+------+----------+
| id   | f        |
+------+----------+
|    1 | ящык     |
+------+----------+
```

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by donhardman** [comment] 2024-12-10 04:37
The given queries are not supported even in our documentation. I'm surprised that it worked for Manticore, but if we look into the documentation for SQL endpoints over HTTP, there is nowhere an example showing that we may use JSON as input instead of GET or POST with URL-encoded form:
![Image](https://github.com/user-attachments/assets/170428ae-0ac8-455e-a7de-f0e7ec7f386f)
https://manual.manticoresearch.com/Connecting_to_the_server/HTTP#/sql

As a final result of this issue, the problem is on the Daemon side. We have never handled that type of queries in buddy when a user sends JSON to SQL because it requires having a plain query or query= with raw URL-encoded form. To solve this, even if we want to introduce this new functionality and support JSON via HTTP SQL endpoints, I believe we should add a fix on the daemon side so it will consistently send us parsed queries, not JSON as it does now, while for raw requests to SQL and CLI it still sends queries.

I believe this issue is not critical because the examples were created outside of documentation and typical users will not do this (unless I'm missing anything).

**Comment by donhardman** [comment] 2024-12-10 07:37
As discussed before we do not have JSON over HTTP for SQL queries, closing the issue

**Closed by donhardman** 2024-12-10 07:37 UTC
Labels: bug
