### ISSUE TITLE
Look into memleak issue while we sending many selects that are routed to buddy

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#167] opened 2023-10-06 04:34 UTC
When we dispatch numerous selects, it appears as though there's a memory leak in the Buddy code. 
This issue could potentially arise when we select from a table that doesn't exist. 
We need to investigate this, identify the cause, and attempt to rectify it.

**Comment by sanikolaev** [comment] 2023-10-06 05:43
Closing as a dupe of https://github.com/manticoresoftware/manticoresearch-buddy/issues/165

**Closed by sanikolaev** 2023-10-06 05:43 UTC
