### ISSUE TITLE
Update the format of ErrorResponse

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/manticoresearch-buddy#204] opened 2024-02-05 16:33 UTC
Currently, the ErrorResponse sent from Buddy to the daemon looks like this:
```
[
  [
    'total' => 0,
    'warning => '',
    'error' => $someError
  ]
]
```

It appears that we don't need to pass 'total' and 'warning' fields with default values here as well as to wrap the 'error' field into array. The following should be enough:
```
[
  'error' => $someError
]
```
In this case we'll be able to keep the same response format with and without Buddy.

**Comment by donhardman** [comment] 2024-02-06 14:54
The daemon works fine with:

```
[BUDDY] [65c247255bfca8.53362414] response data: {"version":1,"type":"sql response","message":[{"total":0,"warning":"","error":"P01: syntax error, unexpected identifier, expecting VARIABLES near 'queries 1'"}],"error":"P01: syntax error, unexpected identifier, expecting VARIABLES near 'queries 1'"}
```

But when we send the next response, the daemon doesn't send it back to the client:

```
[BUDDY] [65c247255bfca8.53362414] response data: {"version":1,"type":"sql response","message":[],"error":"P01: syntax error, unexpected identifier, expecting VARIABLES near 'queries 1'"}
```

The question is whether this is a feature or if we're missing something in the Manticore daemon implementation? It seems like it's what we expect, but it's really confusing. We should consider how to improve this to reduce the confusion caused by multiple errors being defined.

**Comment by donhardman** [comment] 2024-02-07 09:37
I've fixed it, but it looks like the daemon doesn't recognize the change. As a result, I suggest we make it a breaking change in protocol version 2.

```
WARNING: [BUDDY] [186] wrong reply format - not a CLI reply array: {"version":1,"type":"sql response","message":{"error":"You have an error in your query. Please double-check it."},"error":"You have an error in your query. Please double-check it."}
```

However, when executing with curl, it clearly gives a CLI response.

```
root@dev:/workdir# curl -d 'backup' 127.0.0.1:9312/cli
{"error":"You have an error in your query. Please double-check it."}root@dev:/workdir#
```

So, here we can try to apply a hot fix for now that will support both formats (in array and outside array) in the daemon, or we can just wait and include this in the version 2 update. This is because the daemon does not work properly with errors passed without a list. When we return it as `[{"error":"..."}]`, it works.

Here is the pull request with fixes – https://github.com/manticoresoftware/buddy-core/pull/25, tests failed due to Daemon cannot handle proper CLI response from Buddy without list

**Comment by Nick-S-2018** [comment] 2024-02-07 12:28
It seems there are also minor issues with one unit test and the static analysis to be resolved:   https://github.com/manticoresoftware/buddy-core/pull/25

**Comment by donhardman** [comment] 2024-02-08 07:14
As we discussed with Sergey on the call today, we've decided to implement this change starting with protocol v2.

**Comment by donhardman** [comment] 2024-02-08 07:47
Closing the task due to it's migrated to protocol v2 implementation: https://github.com/manticoresoftware/manticoresearch/issues/1806

**Closed by donhardman** 2024-02-08 07:47 UTC
Labels: est::size_S
